services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kusuri
    volumes:
    - "./docker/preprocessing-db/raw_data:/raw_data"
    - type: bind
      source: ./docker/init
      target: /docker-entrypoint-initdb.d
    ports:
      - 8080:5432
  redis:
    image: redis/redis-stack-server:latest
    container_name: kusuri-redis-stack-server
    ports:
      - "6379:6379"
    restart: unless-stopped
