CREATE TABLE "kusuri"."PrescriptionPrompts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "Status" integer NOT NULL,
    "VersionId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "PatientId" integer NOT NULL,
    CONSTRAINT "PK_PrescriptionPrompts" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PrescriptionPrompts_Id_VersionId" ON "PrescriptionPrompts" ("Id", "VersionId");