CREATE TABLE kusuri."PrescriptionPrompt" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ModifiedAt" timestamp with time zone NOT NULL,
    "PatientId" integer NOT NULL,
    CONSTRAINT "PK_PrescriptionPrompt" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_PrescriptionPrompt_Id" ON kusuri."PrescriptionPrompt" ("Id");

CREATE INDEX "IX_PrescriptionPrompt_PatientId" ON kusuri."PrescriptionPrompt" ("PatientId");