CREATE TABLE kusuri."Chat" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Content" text NOT NULL,
    "PatientId" integer NOT NULL,
    "ByBot" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Chat" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Chat_Id" ON kusuri."Chat" ("Id");

CREATE INDEX "IX_Chat_PatientId" ON kusuri."Chat" ("PatientId");